name: crucible-ci

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - LICENSE
      - '**.md'
      - .github/workflows/faux-crucible-ci.yaml
      - 'docs/**'
  workflow_dispatch:

jobs:
  call-tool-crucible-ci:
    uses: perftool-incubator/crucible-ci/.github/workflows/tool-crucible-ci.yaml@main
    with:
      ci_target: "sysstat"
      ci_target_branch: "${{ github.ref }}"
      github_workspace: "$GITHUB_WORKSPACE"
    secrets:
      registry_auth: ${{ secrets.CRUCIBLE_CI_ENGINES_REGISTRY_AUTH }}
